// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoApi.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220703154639_Migracion para el POST")]
    partial class MigracionparaelPOST
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("coin", b =>
                {
                    b.Property<int?>("MonedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("MonedaId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            MonedaId = 1,
                            Descripcion = "Bitcoin Cash",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/3369/PNG/512/bitcoin_cryptocurrency_coin_money_icon_210978.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 2,
                            Descripcion = "Dai",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/2130/PNG/512/dai_cryptocurrency_logo_icon_131454.png",
                            Valor = 8100.0
                        },
                        new
                        {
                            MonedaId = 3,
                            Descripcion = "Polygon",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/3373/PNG/512/polygon_icon_211236.png",
                            Valor = 8100.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
